### ISSUE TITLE
Jumpstats errors

### ISSUE THREAD

**Issue by kmsraidboss** [danzayau/MovementAPI#20]
Ever since the major update that came recently, I've been getting the following spamming in the error logs. Running latest Sourcemod 1.10, latest GOKZ, latest movementAPI. I cannot seem to figure out the problem. 

Also, I don't know if it's related, but since the major update, often times when a player hits the start button, the entire server lags, and there are even instances a couple times per day where the server crashes upon someone pressing the start button. None of this was happening prior to the major update, and I've applied all GOKZ updates since. 

Here is the error that's spamming: 

L 12/25/2019 - 15:57:33: [SM] Exception reported: Array index out-of-bounds (index 32, limit 32)
L 12/25/2019 - 15:57:33: [SM] Blaming: gokz-jumpstats.smx
L 12/25/2019 - 15:57:33: [SM] Call stack trace:
L 12/25/2019 - 15:57:33: [SM]   [1] Line 1142, gokz-jumpstats/jump_tracking.sp::EndStrafes
L 12/25/2019 - 15:57:33: [SM]   [2] Line 136, gokz-jumpstats/jump_tracking.sp::EndJumpstat
L 12/25/2019 - 15:57:33: [SM]   [3] Line 28, gokz-jumpstats/jump_tracking.sp::OnStartTouchGround_JumpTracking
L 12/25/2019 - 15:57:33: [SM]   [4] Line 114, gokz-jumpstats.sp::Movement_OnStartTouchGround
L 12/25/2019 - 15:57:33: [SM]   [6] Call_Finish
L 12/25/2019 - 15:57:33: [SM]   [7] Line 38, movementapi/forwards.sp::Call_OnStartTouchGround
L 12/25/2019 - 15:57:33: [SM]   [8] Line 202, C:\repos\MovementAPI\addons\sourcemod\scripting\movementapi.sp::UpdateOnGround
L 12/25/2019 - 15:57:33: [SM]   [9] Line 125, C:\repos\MovementAPI\addons\sourcemod\scripting\movementapi.sp::OnPlayerPostThinkPost

Any help would be appreciated. I'm more than happy to try anything. I've been troubleshooting it for the past few weeks so I'm hoping you might be able to lend some insight. Thank you so much.

**Comment by kmsraidboss** [comment]
I'm sorry, I'm an idiot. I meant to post this in the GOKZ bitbucket issues section. 

Although, part of the error is from movement API, so maybe it applies here. Still, any help would be appreciated. Will gladly provide any further info needed.

**Comment by kmsraidboss** [comment]
Any idea? This is spamming non stop all day on my servers.

**Comment by danzayau** [comment]
Try the latest GOKZ version (2.6.0) as a fix was attempted. Please make an issue on the GOKZ BitBucket if it persists.

https://bitbucket.org/kztimerglobalteam/gokz/issues/new
