### ISSUE TITLE
Crashes after CSGO Updated

### ISSUE THREAD

**Issue by Nyano1337** [danzayau/MovementAPI#36]
👀

**Comment by 8guawong** [comment]
update sourcemod to 6913 to prevent crash
but gets 

L 10/22/2022 - 14:49:42: [SM] Exception reported: Failed to find CGameMovement::AirAccelerate config
L 10/22/2022 - 14:49:42: [SM] Blaming: movementapi.smx
L 10/22/2022 - 14:49:42: [SM] Call stack trace:
L 10/22/2022 - 14:49:42: [SM]   [0] SetFailState
L 10/22/2022 - 14:49:42: [SM]   [1] Line 190, movementapi\stocks.sp::HookGameMovementFunction
L 10/22/2022 - 14:49:42: [SM]   [2] Line 39, movementapi\hooks.sp::HookGameMovementFunctions
L 10/22/2022 - 14:49:42: [SM]   [3] Line 82, movementapi.sp::HookEvents
L 10/22/2022 - 14:49:42: [SM]   [4] Line 62, movementapi.sp::OnPluginStart
L 10/22/2022 - 14:49:42: [SM] Unable to load plugin "movementapi.smx": Error detected in plugin startup (see error logs)
